---
title: "Announcements"
output: html_notebook
---


### Homework 

- Homework 2 (CH 1 +2), Reading Quiz (CH 3 + 4), and Activity: Tidy Data are due **September 7th at 12 pm ** 

- Turn in Week 1 homework/ reading quiz/ activity if you have not done so already  

  - We will be talking more about GitHub next week
  
  - I will release grades and answers next week
  
### Class Github

Everything I present in class is on GitHub. I encourage you to download the examples I present today and follow along on your own computer. Today we will be going over: 

- course-materials/class-notes/week-01/supplemental-examples.R

-  course-materials/class-notes/week-02/tidyverse-intro.R
  
### Workshops from The Library 

Schedule for Data Management & Research Reproducibility in R workshop series:
 
- September 19: Basics of R and RStudio (2-4 pm) (Optional)

- September 22: Data Wrangling in R (2-4 pm)

- September 29: Data Management and Research Reproducibility in RStudio (1-3 pm)

- October 6: Data Visualization in R (1-3pm)

Sign up here: https://pennstate.qualtrics.com/jfe/form/SV_7OMlGv655KkkU2G